# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Nguyen Quyen Anh
title: Flutter Mobile App Developer
email: anh.nguyenquyen93@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: boxingnguyen
github_username:  boxingnguyen
stackoverflow_username: "4399085"
# dribbble_username: jekyll
facebook_username: QuyenAnh175
# flickr_username: jekyll
instagram_username: brian.nguyen13579
linkedin_username: quyen-anh-nguyen
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Quyen Anh and I'm a Flutter mobile app developer in Hanoi, Vietnam.

  I am most skilled in: <mark>Flutter</mark> and <mark>Eating Pho</mark>

# content:
#   - title: Projects # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: top-middle
#         title: Super awesome project
#         link: github.com/sproogen
#         # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
#           # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#           #   icon: fab fa-github
#           #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#         description: | # this will include new lines to allow paragraphs
#           I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    # content:
    #   - layout: left
    #     title: The Tribal Media House Technology Lab Company
    #     link: tmh-techlab.vn
    #     # link_text: boringcompany.com
    #     sub_title: Developer
    #     caption: November 2016 - February 2021
    #     # quote: >
    #     #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
    #     description: | # this will include new lines to allow paragraphs
    #       - Web Developer(2016 - 2018): Project Engage Manager https://engagemanager.tribalmedia.co.jp/.
    #         Used technologies: Html, Css with bootstrap, js with jquery, mysql & mongodb, php with cakePhp, RESTful API, MVC pattern.
    #       - Ios Developer(2018 - 2019): Ours - Social Internal App (terminated).
    #         Used technologies: Swift, RxSwift, Alamofire, Realm, BLE, MVC pattern.
    #       - Flutter Developer(2019 - Feb 2021): Project NTMY - Business card app https://apps.apple.com/vn/app/ntmy/id1502013921.
    #         Used technologies: Provider, Dio, multi-lang, firebase, testing.
    #       - Self-project: Image classifying uses Raspberry Pi, TensorFlow and python.
    content:
      - layout: left
        title: The GMO-Z.com RUNSYSTEM
        link: runsystem.net
        sub_title: Flutter Team Lead
        caption: March 2021 - Present
        quote: >
          Building beautiful, natively compiled, multi-platform applications from a single codebase.
        description: | # this will include new lines to allow paragraphs
          - Flutter Dveloper: Project ChintaiDx - Realestate mangement system https://chintaidx.com/.
            Team size (dev): 12
            Used technologies: Provider, Graphql, chat system, firebase, graphic, stream, native module.
          - Self-project: NFC mangement.
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hanoi University of Science and Technology (HUST)
        caption: 2012- 2018
        sub_title: Electronics and Telecommunication engineering
        quote: >
          HUST or another lovely Vietnamese name is Bach Khoa (means "teach everything" - 100 department) was founded in 1636, is the first and largest technical university in Vietnam.
        description: | # this will include new lines to allow paragraphs
          During my time at HUST I learned how big the world is, how ebb and flow of life is, how crazy of youth is and how to love and be loved.

          I spent a lot of my free time as an member of the *Bach Khoa voluntary blood donation Team* taking on roles as *Captain*. Moreover, I also take part in activity that help new student to find motel.
          And I can't forget the green terraced fields when I went to remote areas to help ethnic minorities.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Flutter and technology some of my other interests and hobbies are:
      - Swimming & footbal
      - Backpacking
      - Rock & epic music
      - Poetry
      - Detective novel and film
      - Gaming

      Look at this cool image  
      ![Trees](https://www.pinterest.com/pin/405886985139418794/ "Strong")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
